### ISSUE TITLE
[Bug]: Puppeteer doesn't convert python string to f-string when inserting `{}` 

### ISSUE THREAD

**Issue by TroySigX** [chrisgrieser/nvim-puppeteer#17]
### Bug Description

As title

### To Reproduce

Enter this in a `python` file: 
```python
x = '123{t}'
```

### neovim version

```Text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
fixed

**Comment by TroySigX** [comment]
Can you check again, I still have the problem. I already updated to the latest commit.

**Comment by TroySigX** [comment]
Oh, it is because I put `event = 'VeryLazy'` in `lazy.nvim`, nevermind, thank you for the quick fix.
